# Vector and Matrix Multiplication

In [2]:
import pandas as pd
import numpy as np

## Vector . Vector 

* The probability of tomorrow being cold given today is cold is 0.4
* The probability of tomorrow being cold given today is hot is 0.6
* The probability of today being cold is 0.9 and of being hot is 0.1

What is the probability of tomorrow being cold ?



In [5]:
#0th index is cold, and 1th index is hot
today = np.array([0.9, 0.1])
is_tomorrow_cold = np.array([0.4, 0.6])

In [6]:
# get the product of the two matricies
today * is_tomorrow_cold

array([0.36, 0.06])

In [7]:
# sum of products / dot product 
(today * is_tomorrow_cold).sum()

0.42000000000000004

In [8]:
# numpy version
np.dot(today, is_tomorrow_cold)

0.42000000000000004

The dot product of Vector and Vector gives a number

### Vector .  Matrix 

![](matrix.png)

In [9]:
#0th index is cold, and 1th index is hot
today = np.array([1, 0])
transition_matrix = np.array([[0.4, 0.6], [0.67, 0.33]])

In [10]:
np.dot(today, transition_matrix)

array([0.4, 0.6])

The dot product of Matrix . Vector -> Vector

### Matrix . Matrix

In [11]:
X = np.random.rand(2, 3)
X.shape

(2, 3)

In [12]:
X

array([[0.54348475, 0.68079799, 0.8812141 ],
       [0.16701434, 0.2916596 , 0.59007745]])

In [13]:
Y = np.random.rand(2, 3) * 2
Y.shape

(2, 3)

In [14]:
Y

array([[1.90739179, 0.50415447, 0.0207343 ],
       [0.88450871, 1.56944989, 1.41190556]])

In [15]:
# will this work ?
np.dot(X, Y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Dot product of matricies has to have the following shape

(A, B) . (B, C) and this will give a matrix with shape (A, C)

In [16]:
# so how can change the shape of the second matrix to make this work ?
# tarnspose 
Y.T

array([[1.90739179, 0.88450871],
       [0.50415447, 1.56944989],
       [0.0207343 , 1.41190556]])

We are doing the transpose here as an example, however, when you working problems in deep learning, where we will calculate a lot of dot product of matricies, you have to be sure that you are multiplying the right quantaties together

In [17]:
(X.shape, Y.T.shape)

((2, 3), (3, 2))

In [18]:
# now try again
np.dot(X, Y.T)

array([[1.39813706, 2.79338642],
       [0.47783812, 1.4386044 ]])

The dot product of 2 matricies is a matrix with a shape of (A,C) where the first matrix shape is (A, B) and the second matrix shape is (B, C)